// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;


// SCREEN: ui_Function_Screen
void ui_Function_Screen_screen_init(void);
void ui_event_Function_Screen(lv_event_t * e);
lv_obj_t * ui_Function_Screen;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label11;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Button3;
void ui_event_Label5(lv_event_t * e);
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label12;


// SCREEN: ui_HomeAutomation
void ui_HomeAutomation_screen_init(void);
void ui_event_HomeAutomation(lv_event_t * e);
lv_obj_t * ui_HomeAutomation;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Switch3;


// SCREEN: ui_AlarmClock
void ui_AlarmClock_screen_init(void);
lv_obj_t * ui_AlarmClock;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Roller6;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Roller2;
lv_obj_t * ui_Addbttn;
void ui_event_bttn9(lv_event_t * e);
lv_obj_t * ui_bttn9;


// SCREEN: ui_Alarmcheck
void ui_Alarmcheck_screen_init(void);
void ui_event_Alarmcheck(lv_event_t * e);
lv_obj_t * ui_Alarmcheck;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;


// SCREEN: ui_AlarmDisplay
void ui_AlarmDisplay_screen_init(void);
void ui_event_AlarmDisplay(lv_event_t * e);
lv_obj_t * ui_AlarmDisplay;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;


// SCREEN: ui_ringRing
void ui_ringRing_screen_init(void);
void ui_event_ringRing(lv_event_t * e);
lv_obj_t * ui_ringRing;


// SCREEN: ui_StopWatchSD
void ui_StopWatchSD_screen_init(void);
void ui_event_StopWatchSD(lv_event_t * e);
lv_obj_t * ui_StopWatchSD;
lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Switch1;


// SCREEN: ui_TabStop
void ui_TabStop_screen_init(void);
lv_obj_t * ui_TabStop;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Roller3;
lv_obj_t * ui_Roller4;
lv_obj_t * ui_Roller5;
lv_obj_t * ui_AddStopWatch;
void ui_event_bttn1(lv_event_t * e);
lv_obj_t * ui_bttn1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_337665095[1] = {&ui_img_1258245280};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Function_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 0, &ui_Function_Screen_screen_init);
    }
}
void ui_event_Function_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_HomeAutomation, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeAutomation_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Alarmcheck, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Alarmcheck_screen_init);
    }
}
void ui_event_Label5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Alarmcheck, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Alarmcheck_screen_init);
    }
}
void ui_event_HomeAutomation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_bttn9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_AlarmDisplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlarmDisplay_screen_init);
    }
}
void ui_event_Alarmcheck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_AlarmDisplay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlarmDisplay_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_StopWatchSD, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StopWatchSD_screen_init);
    }
}
void ui_event_AlarmDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_AlarmClock, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlarmClock_screen_init);
    }
}
void ui_event_ringRing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_StopWatchSD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Alarmcheck, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 0, &ui_Alarmcheck_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 400, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_TabStop, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TabStop_screen_init);
    }
}
void ui_event_bttn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_StopWatchSD, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StopWatchSD_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Function_Screen_screen_init();
    ui_HomeAutomation_screen_init();
    ui_AlarmClock_screen_init();
    ui_Alarmcheck_screen_init();
    ui_AlarmDisplay_screen_init();
    ui_ringRing_screen_init();
    ui_StopWatchSD_screen_init();
    ui_TabStop_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
