// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Function_Screen
void ui_Function_Screen_screen_init(void);
void ui_event_Function_Screen(lv_event_t * e);
extern lv_obj_t * ui_Function_Screen;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label11;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button3;
void ui_event_Label5(lv_event_t * e);
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_HomeAutomation
void ui_HomeAutomation_screen_init(void);
void ui_event_HomeAutomation(lv_event_t * e);
extern lv_obj_t * ui_HomeAutomation;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Switch3;
// SCREEN: ui_AlarmClock
void ui_AlarmClock_screen_init(void);
extern lv_obj_t * ui_AlarmClock;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Roller6;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Addbttn;
void ui_event_bttn9(lv_event_t * e);
extern lv_obj_t * ui_bttn9;
// SCREEN: ui_Alarmcheck
void ui_Alarmcheck_screen_init(void);
void ui_event_Alarmcheck(lv_event_t * e);
extern lv_obj_t * ui_Alarmcheck;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_AlarmDisplay
void ui_AlarmDisplay_screen_init(void);
void ui_event_AlarmDisplay(lv_event_t * e);
extern lv_obj_t * ui_AlarmDisplay;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
// SCREEN: ui_ringRing
void ui_ringRing_screen_init(void);
void ui_event_ringRing(lv_event_t * e);
extern lv_obj_t * ui_ringRing;
// SCREEN: ui_StopWatchSD
void ui_StopWatchSD_screen_init(void);
void ui_event_StopWatchSD(lv_event_t * e);
extern lv_obj_t * ui_StopWatchSD;
extern lv_obj_t * ui_Label13;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Switch1;
// SCREEN: ui_TabStop
void ui_TabStop_screen_init(void);
extern lv_obj_t * ui_TabStop;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Roller5;
extern lv_obj_t * ui_AddStopWatch;
void ui_event_bttn1(lv_event_t * e);
extern lv_obj_t * ui_bttn1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1258245280);    // assets/Screenshot 2024-06-16 040750.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
