// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_AlarmClock_screen_init(void)
{
    ui_AlarmClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AlarmClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AlarmClock, lv_color_hex(0x5E0873), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AlarmClock, lv_color_hex(0x1C032C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AlarmClock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AlarmClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AlarmClock, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_AlarmClock);
    lv_obj_set_width(ui_Panel7, 199);
    lv_obj_set_height(ui_Panel7, 207);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller6 = lv_roller_create(ui_AlarmClock);
    lv_roller_set_options(ui_Roller6,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller6, 100);
    lv_obj_set_width(ui_Roller6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller6, 61);
    lv_obj_set_y(ui_Roller6, 5);
    lv_obj_set_align(ui_Roller6, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller6, lv_color_hex(0xFA0CD8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller6, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_AlarmClock);
    lv_roller_set_options(ui_Roller1, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 8);
    lv_obj_set_y(ui_Roller1, 4);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFA0FD0), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_AlarmClock);
    lv_roller_set_options(ui_Roller2, "Mon\nTue\nWed\nThur\nFri\nSat\nSun", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller2, 100);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, -59);
    lv_obj_set_y(ui_Roller2, 1);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Roller2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xEF0BDF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Addbttn = lv_btn_create(ui_AlarmClock);
    lv_obj_set_width(ui_Addbttn, 34);
    lv_obj_set_height(ui_Addbttn, 16);
    lv_obj_set_x(ui_Addbttn, -57);
    lv_obj_set_y(ui_Addbttn, -60);
    lv_obj_set_align(ui_Addbttn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Addbttn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Addbttn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bttn9 = lv_btn_create(ui_AlarmClock);
    lv_obj_set_width(ui_bttn9, 34);
    lv_obj_set_height(ui_bttn9, 16);
    lv_obj_set_x(ui_bttn9, 58);
    lv_obj_set_y(ui_bttn9, -60);
    lv_obj_set_align(ui_bttn9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bttn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bttn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_bttn9, ui_event_bttn9, LV_EVENT_ALL, NULL);

}
