// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TabStop_screen_init(void)
{
    ui_TabStop = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TabStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabStop, lv_color_hex(0x5E0873), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_TabStop, lv_color_hex(0x1C032C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_TabStop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_TabStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_TabStop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_TabStop);
    lv_obj_set_width(ui_Panel1, 199);
    lv_obj_set_height(ui_Panel1, 207);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller3 = lv_roller_create(ui_TabStop);
    lv_roller_set_options(ui_Roller3,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller3, 100);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller3, 57);
    lv_obj_set_y(ui_Roller3, 1);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0xFA0CD8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller4 = lv_roller_create(ui_TabStop);
    lv_roller_set_options(ui_Roller4,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller4, 100);
    lv_obj_set_width(ui_Roller4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller4, -2);
    lv_obj_set_y(ui_Roller4, -1);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0xFA0FD0), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller4, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Roller5 = lv_roller_create(ui_TabStop);
    lv_roller_set_options(ui_Roller5, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller5, 100);
    lv_obj_set_width(ui_Roller5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller5, -59);
    lv_obj_set_y(ui_Roller5, 1);
    lv_obj_set_align(ui_Roller5, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Roller5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller5, lv_color_hex(0xEF0BDF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller5, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_AddStopWatch = lv_btn_create(ui_TabStop);
    lv_obj_set_width(ui_AddStopWatch, 34);
    lv_obj_set_height(ui_AddStopWatch, 16);
    lv_obj_set_x(ui_AddStopWatch, -57);
    lv_obj_set_y(ui_AddStopWatch, -60);
    lv_obj_set_align(ui_AddStopWatch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddStopWatch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddStopWatch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AddStopWatch, lv_color_hex(0xFC09BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddStopWatch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bttn1 = lv_btn_create(ui_TabStop);
    lv_obj_set_width(ui_bttn1, 34);
    lv_obj_set_height(ui_bttn1, 16);
    lv_obj_set_x(ui_bttn1, 58);
    lv_obj_set_y(ui_bttn1, -60);
    lv_obj_set_align(ui_bttn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bttn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bttn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bttn1, lv_color_hex(0xFA15DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bttn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bttn1, ui_event_bttn1, LV_EVENT_ALL, NULL);

}
